services:
    geo-api:
      container_name: geo-api
      image: geoapi:prd
      build: .
      restart: always
      volumes:
        - ./app:/home/jonnattan/app
      ports:
        - "8075:8075"
      env_file:
        - ../envs/file_geo.env
      networks:
        - db-net
      # command: tail -f /home/jonnattan/requirements.txt
networks:
  db-net:
