services:
    geo-api:
      container_name: geo-api
      image: jonnattangc/geoservice:1.0.0
      #build: .
      restart: none
      #volumes:
      #  - ./app:/home/jonnattan/app
      ports:
        - "8075:8075"
      env_file:
        - ../envs/geo.env
      networks:
        - db-net
      #command: tail -f /home/jonnattan/requirements.txt
networks:
  db-net:
